version: '3'

services:
  db:
    image: postgres
    restart: always
#    ports:
#      - '5103:5103'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    build: .
    #build: ./docker-compose/server_flask
    restart: always
    ports:
      - '8009:8009'
    depends_on:
      - db



#version: '3'
#services:
#  app:
#    build: .
#    ports:
#      - "5000:5000"
#    depends_on:
#      - db
#    environment:
#      - DATABASE_HOST=db
#      - DATABASE_PORT=5432
#      - DATABASE_NAME=postgres
#      - DATABASE_USER=postgres
#      - DATABASE_PASSWORD=password
#  db:
#    image: postgres
#    restart: always
#    environment:
#      - POSTGRES_DB=your_database
#      - POSTGRES_USER=your_username
#      - POSTGRES_PASSWORD=your_password
