version: '3'

services:
  db:
    build:
      context: data_base
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: always
#    volumes:
#      - ./app:/app
#    depends_on:
#      - db
